stages:
  - build
  - test
  - security
  - policy
  - deploy

variables:
  DOCKER_DRIVER: overlay2
  DOCKER_TLS_CERTDIR: "/certs"
  IMAGE_NAME: $CI_REGISTRY_IMAGE
  IMAGE_TAG: $CI_COMMIT_SHORT_SHA
  TRIVY_CACHE_DIR: .trivycache

# Build stage
build:
  stage: build
  image: docker:24
  services:
    - docker:24-dind
  before_script:
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "Building Docker image: $IMAGE_NAME:$IMAGE_TAG"
    - docker build -t $IMAGE_NAME:$IMAGE_TAG .
    - docker tag $IMAGE_NAME:$IMAGE_TAG $IMAGE_NAME:latest
    - docker push $IMAGE_NAME:$IMAGE_TAG
    - docker push $IMAGE_NAME:latest
  only:
    - main
    - master
    - merge_requests

# Security scanning stage
trivy-scan:
  stage: security
  image: aquasec/trivy:latest
  dependencies:
    - build
  script:
    - mkdir -p $TRIVY_CACHE_DIR
    - |
      trivy image \
        --cache-dir $TRIVY_CACHE_DIR \
        --format template --template "@contrib/gitlab.tpl" \
        -o gl-container-scanning-report.json \
        --exit-code 0 \
        --severity CRITICAL,HIGH,MEDIUM,LOW \
        $IMAGE_NAME:$IMAGE_TAG || true
    - |
      trivy image \
        --cache-dir $TRIVY_CACHE_DIR \
        --format table \
        --severity CRITICAL,HIGH,MEDIUM,LOW \
        $IMAGE_NAME:$IMAGE_TAG || true
  artifacts:
    reports:
      container_scanning: gl-container-scanning-report.json
    paths:
      - gl-container-scanning-report.json
    expire_in: 1 week
  allow_failure: false
  only:
    - main
    - master
    - merge_requests

# Secret scanning
trivy-secret:
  stage: security
  image: aquasec/trivy:latest
  dependencies:
    - build
  script:
    - |
      trivy image \
        --cache-dir $TRIVY_CACHE_DIR \
        --security-checks secret \
        --format table \
        --exit-code 1 \
        $IMAGE_NAME:$IMAGE_TAG
  allow_failure: false
  only:
    - main
    - master
    - merge_requests

# Misconfiguration scanning
trivy-config:
  stage: security
  image: aquasec/trivy:latest
  dependencies:
    - build
  script:
    - |
      trivy image \
        --cache-dir $TRIVY_CACHE_DIR \
        --security-checks config \
        --format table \
        --exit-code 1 \
        $IMAGE_NAME:$IMAGE_TAG
  allow_failure: false
  only:
    - main
    - master
    - merge_requests

# Policy enforcement stage
policy-check:
  stage: policy
  image: docker:24
  services:
    - docker:24-dind
  dependencies:
    - build
  before_script:
    - apk add --no-cache jq
    - docker login -u $CI_REGISTRY_USER -p $CI_REGISTRY_PASSWORD $CI_REGISTRY
  script:
    - echo "Checking security policies..."
    
    # Check for critical/high vulnerabilities (fail on these)
    - |
      if trivy image --cache-dir $TRIVY_CACHE_DIR \
        --exit-code 1 \
        --severity CRITICAL,HIGH \
        --no-progress \
        $IMAGE_NAME:$IMAGE_TAG 2>&1 | grep -q "CRITICAL\|HIGH"; then
        echo "Policy violation: Critical or High severity vulnerabilities found"
        exit 1
      fi
    
    # Verify base image is from approved registry
    - |
      BASE_IMAGE=$(docker inspect $IMAGE_NAME:$IMAGE_TAG | jq -r '.[0].Config.Image')
      APPROVED_REGISTRIES="docker.io/library gcr.io registry.example.com"
      IS_APPROVED=false
      for registry in $APPROVED_REGISTRIES; do
        if echo "$BASE_IMAGE" | grep -q "^$registry"; then
          IS_APPROVED=true
          break
        fi
      done
      if [ "$IS_APPROVED" = false ]; then
        echo "Policy violation: Base image must be from approved registry"
        echo "Base image: $BASE_IMAGE"
        exit 1
      fi
    
    # Check if container runs as root
    - |
      USER_ID=$(docker inspect $IMAGE_NAME:$IMAGE_TAG | jq -r '.[0].Config.User // "root"')
      if [ "$USER_ID" = "root" ] || [ "$USER_ID" = "0" ]; then
        echo "Policy violation: Container must not run as root user"
        echo "Current user: $USER_ID"
        exit 1
      fi
    
    # Check for resource limits in Dockerfile
    - |
      if ! grep -q "USER\|--user" Dockerfile 2>/dev/null; then
        echo "Warning: No non-root user specified in Dockerfile"
      fi
    
    - echo "All policy checks passed"
  allow_failure: false
  only:
    - main
    - master
    - merge_requests

# Deploy stage (only on main/master after all checks pass)
deploy:
  stage: deploy
  image: docker:24
  services:
    - docker:24-dind
  dependencies:
    - build
  script:
    - echo "Deploying $IMAGE_NAME:$IMAGE_TAG"
    - echo "Deployment would occur here"
    # Add your deployment commands
  only:
    - main
    - master
  when: on_success

